services:

  - type: web
    name: weather-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app

  - type: cron
    name: weather-updater
    env: python
    schedule: "0 */6 * * *"
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
